# Autogenerated by nbdev

d = { 'settings': { 'doc_baseurl': '/cop_diffusion',
                'doc_host': 'https://jean-kunz.github.io',
                'git_url': 'https://github.com/jean-kunz/cop_diffusion',
                'lib_path': 'cop_diffusion'},
  'syms': {'cop_diffusion.start': {}}}
